name: "Update Mythril and Dependency Versions"
on:
  workflow_dispatch:
  schedule: # daily
    - cron: 39 4 * * *

jobs:
  update-dependencies:
    name: Build Without Publishing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: |
          pip install -r requirements-dev.txt

      - name: Update Dependency Versions
        run: |
          [[ $(git status --porcelain) == "" ]] || {
            echo "git checkout is not clean before updating";
            exit 1;
          }
          poetry lock
          python gen_version_vars.py > docker-bake.versions.json

          echo "dependencies_changed=$(\
            [[ $(git status --porcelain) != "" ]] && echo true || echo false
          )" >> "$GITHUB_ENV"

      - name: Create Pull Request for Dependency Changes
        uses: peter-evans/create-pull-request@v5
        if: ${{ env.dependencies_changed == true }}
        with:
          commit-message: "chore: auto-update dependencies"
          title: 🤖 Update Dependencies
          branch: auto-update-dependencies
          labels: "dependency-update,automated"
          body:
