name: "Auto-merge Dependabot PR"
on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  update-dependencies:
    name: Update Dependencies & PR if Changed
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Auto-merge Dependabot PR
        if: |
          startswith(github.event.pull_request.title, 'build(deps): bump')
        run: gh pr merge --auto --merge "${PULL_REQUEST:?}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST: ${{ github.event.pull_request.url }}
